version: '2'
services:
    market-app:
        image: market
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://market-mysql:3306/market?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=market-elasticsearch:9300
        ports:
            - 8080:8080
    market-mysql:
        extends:
            file: mysql.yml
            service: market-mysql
    market-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: market-elasticsearch
