version: '2'
services:
    marketplacejhipster-app:
        image: marketplacejhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://marketplacejhipster-mysql:3306/marketplacejhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=marketplacejhipster-elasticsearch:9300
        ports:
            - 8080:8080
    marketplacejhipster-mysql:
        extends:
            file: mysql.yml
            service: marketplacejhipster-mysql
    marketplacejhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: marketplacejhipster-elasticsearch
