version: '2'
services:
    marketplacejhipster-mysql:
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/marketplacejhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=marketplacejhipster
        ports:
        
            - 3306:3306 # host:container
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
